# config/packages/fos_user.yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entities\User
    from_email:
        address: "test@domain.com"
        sender_name: "test@domain.com"